version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      DB_SERVICE: "db"
    ports:
      - "8000:8000"
#    command: bash -c "sleep 5000"

volumes:
  db-data:

